#ifndef COLOR_KEY_H
# define COLOR_KEY_H

# define BLACK 0x000000
# define WHITE 0xFFFFFF
# define SILVER 0xC0C0C0
# define GOLDEN_ROD 0xDAA520
# define AQUA_MARINE 0x7FFFD4
# define DARK_MAGENTA 0x8B008B
# define ORCHID 0xFF83FA
# define ANTIQUE_WHITE 0xFAEBD7
# define LAVENDER 0xE6E6FA
# define MISTY_ROSE 0xFFE4E1
# define GAINSBORO 0xDCDCDC
# define SPRING_GREEN 0x00FF7F

#endif